branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: srm_event
  default_ec2_keyname: null
  default_platform: Python 2.7
  default_region: us-west-2
  profile: eb-cli
  sc: git
